#theme: jekyll-theme-minimal
url: "your_site_url"
title: "your_site_title"
logo: assets/images/logo.jpg
plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
google_analytics: "your_google_analytics_id"

markdown: kramdown
kramdown:
  input: GFM
  hard_wrap: true
highlighter: rouge
